# -*- coding: utf-8 -*-
"""SNaC: Summary Narrative Coherence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MElK6evfIZRqMnPi9eGTYZ_EMMl3nyC8
"""

!git clone https://github.com/tagoyal/snac.git

!pip install transformers

from google.colab import drive
drive.mount('/content/gdrive')

!pip install sentencepiece

!python3 /content/snac/snac_evaluate.py --validation_file /content/snac/sample.tsv --model_name_or_path /content/snac/SNac_data_models/t5-span --output_dir /content/snac/[output_dir]

!python3 /content/snac/snac_evaluate.py --validation_file /content/snac/sample.tsv --model_name_or_path  /content/snac/SNac_data_models/t5-nospan  --output_dir /content/snac/[output_dir]